### PR TITLE
assert cwd

### PR DESCRIPTION
**Pull request by janezj**
Prevent silent cwd failure

### CODE REVIEW

**Comment by miner** [comment]
I don't want the assert there.  I'm not sure if it should throw or just be a warning. I will have to think about it.  In any case, I won't take any changes that don't have corresponding tests.

**Comment by janezj** [comment]
> I don't want the assert there. I'm not sure if it should throw or just be a warning. I will have to think about it.
(with-ftp "ftp://a:b@examplecom//private" ; there is no guarantee that you are actually  in /private folder, it could be a default folder of ftp server) . Reason can be typo ( /private instead of //private )  or because of inaccessibility of /private folder. 

Currently, it is impossible to be sure if the current folder is the one stated in url.

**Comment by miner** [comment]
Just FYI: `client-pwd` should give you the current path as a string.  

I agree with the original point that it should be an error if you can't connect to the directory in the given URL.  I will put a check for that and throw an error if it fails.

**Comment by miner** [comment]
Released [com.velisco/clj-ftp "0.3.17"] with the fix.

**Pull request closed without merging**
