### PR TITLE
Add security-mode option

### PR DESCRIPTION
**Pull request by borkdude**
Since this pull request https://github.com/miner/clj-ftp/pull/30 is lagging a bit behind I decided to make a new pull request with only this option. Any chance of merging this soon?

### CODE REVIEW

**Comment by miner** [comment]
I asked for a test in the old PR and got no response. Honestly, I just forgot about it after that.  I would definitely take a PR with a reasonable test.  Can you provide a test?  Or at least tell me that you tested in your private environment?

**Comment by borkdude** [comment]
I tested in my private environment.
I have no idea how to test this without providing an FTP server that requires implicit security-mode. Mocking would be an option, but not so useful. What could be a test is when you pass `:security-mode` `:implicit` that the  `FTPSClient` has the implicit boolean set to true, but this class doesn't expose that boolean.

https://commons.apache.org/proper/commons-net/apidocs/src-html/org/apache/commons/net/ftp/FTPSClient.html#line.138

**Comment by borkdude** [comment]
An idea would be to use https://mina.apache.org/ftpserver-project/embedding_ftpserver.html for testing, since the mock ftp library also doesn't provide an implicit SSL option. But even the library that we are wrapping doesn't have a test for this: https://github.com/apache/commons-net/tree/trunk/src/test/java/org/apache/commons/net/ftp

**Comment by borkdude** [comment]
>  I would definitely take a PR with a reasonable test. Can you provide a test? Or at least tell me that you tested in your private environment?

I have tested it in my private environment. All it does is add an extra option which will be used in as a constructor argument in the `FTPSClient`. Apache Commons Net doesn't have a unit test for this either.

**Comment by miner** [comment]
OK, I'll take your word for it.

**Comment by borkdude** [comment]
Thanks!

**Pull request merged**
